spring.application.name=spring-itext-pdf-generation
server.port=9000

logging.level.root=info
logging.level.org.springframework=debug
logging.level.com.itext.pdf.generation.*=debug


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=suresh
spring.datasource.username=sa
spring.datasource.password=dockerStrongPwd123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=false
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



